import { useMemo } from 'react'
import { textToHtml } from '../utils/docParser.js'
import './DocxPreview.css'

/**
 * Renders all draft sections as a live A4-style document preview,
 * matching the EBA tender response design (navy cover, blue headings,
 * justified body text, professional tables).
 */
export default function DocxPreview({ sections = [], filename = 'Tender Response', activeSectionId = null }) {
  const sectionsHtml = useMemo(() =>
    sections.map(s => ({
      ...s,
      html: textToHtml(s.finalised_content || s.user_edits || s.draft_text || ''),
    })),
    [sections]
  )

  return (
    <div className="docx-page-wrap">
      <div className="docx-page">
        {/* Cover header */}
        <div className="docx-cover">
          <div className="docx-cover-category">Technical</div>
          <h1 className="docx-cover-title">{filename.replace(/\.(pdf|docx|txt)$/i, '')}</h1>
          <div className="docx-cover-org">Meridian Intelligence GmbH</div>
        </div>

        {/* Meta row */}
        <div className="docx-meta-row">
          <span className="docx-meta-label">Generated by</span>
          <span className="docx-meta-value">TenderFlow AI Agent</span>
        </div>

        {/* Sections */}
        <div className="docx-body">
          {sectionsHtml.length === 0 ? (
            <p className="docx-empty">Sections will appear here once drafted.</p>
          ) : (
            sectionsHtml.map((s, idx) => (
              <div
                key={s.section_id}
                id={`preview-${s.section_id}`}
                className={`docx-section ${activeSectionId === s.section_id ? 'docx-section--active' : ''}`}
              >
                <h2 className="docx-section-heading">
                  {s.section_name}
                </h2>
                <div
                  className="docx-section-body"
                  dangerouslySetInnerHTML={{ __html: s.html }}
                />
                {s.sources_used?.length > 0 && (
                  <div className="docx-sources">
                    <span className="docx-sources-label">Sources:</span>
                    {s.sources_used.map((src, i) => (
                      <span key={i} className="docx-source-tag">{src}</span>
                    ))}
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}
