"""
DOCX output renderer.

Converts TenderState into a professionally formatted Word document:
  Cover page          — title, date, final readiness score + band
  Readiness Assessment — score table (Primary / Compliance / Robustness / Final)
                         + score justifications
                         + Action Items checklist (gap flags)
  Tender Sections     — one heading-2 per section, confidence indicator,
                         gap warning (if any), body text, sources footer

Content priority per section:
  finalised_content  (post-HITL Sonnet polish)
  > user_edits       (raw human edits, used if finalise didn't run)
  > draft_text       (original AI draft)

python-docx is used directly — no system-level PDF dependencies needed.
"""

import logging
import os
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from config.settings import settings

logger = logging.getLogger(__name__)

# ── Colour palette ─────────────────────────────────────────────────────────────
_BAND_COLOURS: dict[str, RGBColor] = {
    "EXCELLENT": RGBColor(0x27, 0xAE, 0x60),
    "STRONG": RGBColor(0x29, 0x80, 0xB9),
    "MODERATE": RGBColor(0xF3, 0x9C, 0x12),
    "WEAK": RGBColor(0xE7, 0x4C, 0x3C),
}
_GREY = RGBColor(0x7F, 0x8C, 0x8D)
_WARN_COLOUR = RGBColor(0xE7, 0x4C, 0x3C)

_CONFIDENCE_LABELS = {
    "HIGH": "[HIGH CONFIDENCE]",
    "MEDIUM": "[MEDIUM CONFIDENCE]",
    "LOW": "[LOW CONFIDENCE]",
}


_XML_ILLEGAL = re.compile(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]')


def _sanitize(text: str) -> str:
    """Strip XML-illegal control characters that would corrupt DOCX XML."""
    return _XML_ILLEGAL.sub('', text).replace('\r\n', '\n').replace('\r', '\n')


def _score_band(score: float) -> str:
    if score >= 90:
        return "EXCELLENT"
    if score >= 75:
        return "STRONG"
    if score >= 60:
        return "MODERATE"
    return "WEAK"


# ── Public entry point ─────────────────────────────────────────────────────────

def render_docx(state: dict, tender_id: str) -> str:
    """
    Render a complete tender response DOCX from the agent state dict.

    Args:
        state:     TenderState dict (serialisable subset — no LangGraph internals).
        tender_id: Used as the output filename.

    Returns:
        Absolute path to the saved .docx file.
    """
    os.makedirs(settings.outputs_dir, exist_ok=True)
    output_path = str(Path(settings.outputs_dir) / f"{tender_id}.docx")

    doc = Document()
    _configure_styles(doc)
    _add_cover(doc, state)
    doc.add_page_break()
    _add_readiness_assessment(doc, state)
    doc.add_page_break()

    for section in state.get("sections", []):
        _add_section(doc, section)

    doc.save(output_path)
    logger.info(f"[output] DOCX saved → {output_path}")
    return output_path


# ── Document sections ──────────────────────────────────────────────────────────

def _configure_styles(doc: Document) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)


def _add_cover(doc: Document, state: dict) -> None:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("TENDER RESPONSE — FIRST DRAFT")
    run.bold = True
    run.font.size = Pt(22)

    doc.add_paragraph()

    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p2.add_run("Meridian Intelligence GmbH")
    p2.add_run().add_break()  # soft line break — keeps same paragraph, no \n in XML
    p2.add_run(datetime.now().strftime('%B %d, %Y'))

    final_score = state.get("final_score", 0.0)
    band = _score_band(final_score)
    colour = _BAND_COLOURS[band]

    doc.add_paragraph()
    p3 = doc.add_paragraph()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run3 = p3.add_run(f"Readiness Score:  {final_score:.1f} / 100  —  {band}")
    run3.bold = True
    run3.font.size = Pt(14)
    run3.font.color.rgb = colour

    doc.add_paragraph()
    p4 = doc.add_paragraph()
    p4.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p4.add_run(
        "Generated by TenderFlow · For internal review only · Do not submit without human review"
    ).italic = True


def _add_readiness_assessment(doc: Document, state: dict) -> None:
    doc.add_heading("Readiness Assessment", level=1)

    # Score summary table
    score_rows = [
        ("Primary Score (Track Record + Expertise + Methodology)", state.get("primary_score_total", 0.0)),
        ("Compliance Coverage", state.get("compliance_score", 0.0)),
        ("Robustness Index", state.get("robustness_score", 0.0)),
        ("Final Score", state.get("final_score", 0.0)),
    ]

    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Shading Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Dimension"
    hdr[1].text = "Score"
    hdr[2].text = "Band"
    for hdr_cell in hdr:
        for run in hdr_cell.paragraphs[0].runs:
            run.bold = True

    for dimension, score in score_rows:
        row = table.add_row().cells
        row[0].text = dimension
        row[1].text = f"{score:.1f} / 100"
        band = _score_band(score)
        row[2].text = band

    doc.add_paragraph()

    # Module breakdown table (M1-M5)
    primary_scores = state.get("primary_scores", {})
    if primary_scores:
        doc.add_heading("Primary Score Breakdown", level=2)
        _MODULE_LABELS = {
            "M1_track_record": "Track Record — past project similarity",
            "M2_expertise_depth": "Expertise Depth — domain & regulatory coverage",
            "M3_methodology_fit": "Methodology Fit — approach alignment",
            "M4_delivery_credibility": "Delivery Credibility — team CV match",
            "M5_pricing": "Pricing Proxy — budget competitiveness",
        }
        mod_table = doc.add_table(rows=1, cols=3)
        mod_table.style = "Light Shading Accent 1"
        mhdr = mod_table.rows[0].cells
        mhdr[0].text = "Module"
        mhdr[1].text = "Score"
        mhdr[2].text = "Band"
        for c in mhdr:
            for run in c.paragraphs[0].runs:
                run.bold = True
        for key, label in _MODULE_LABELS.items():
            score = primary_scores.get(key)
            if score is None:
                continue
            mrow = mod_table.add_row().cells
            mrow[0].text = label
            mrow[1].text = f"{score:.0f} / 100"
            mrow[2].text = _score_band(score)
        doc.add_paragraph()

    # Score justifications
    justifications = state.get("score_justifications", {})
    if justifications:
        doc.add_heading("Score Justifications", level=2)
        for module, justification in justifications.items():
            p = doc.add_paragraph()
            p.add_run(f"{module}:  ").bold = True
            p.add_run(_sanitize(str(justification)))

    # Action Items — gap flags + LOW-confidence sections
    doc.add_heading("Action Items", level=2)
    sections = state.get("sections", [])
    gap_sections   = [s for s in sections if s.get("gap_flag")]
    low_no_gap     = [s for s in sections if s.get("confidence") == "LOW" and not s.get("gap_flag")]

    if gap_sections or low_no_gap:
        for s in gap_sections:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"[{s['section_name']}]  ")
            run.bold = True
            run.font.color.rgb = _WARN_COLOUR
            p.add_run(s["gap_flag"])
        for s in low_no_gap:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"[{s['section_name']}]  ")
            run.bold = True
            run.font.color.rgb = _WARN_COLOUR
            p.add_run(
                "Low-confidence draft — KB content found via fallback retrieval only. "
                "Review and supplement with project-specific evidence."
            )
    else:
        doc.add_paragraph("No critical knowledge-base gaps identified for this tender.")


def _add_section(doc: Document, section: dict) -> None:
    section_name = section.get("section_name", "Untitled Section")
    confidence = section.get("confidence", "MEDIUM")
    gap_flag = section.get("gap_flag")

    # Heading with inline confidence indicator
    heading = doc.add_heading(level=2)
    heading.add_run(_sanitize(section_name))
    conf_run = heading.add_run(f"   {_CONFIDENCE_LABELS.get(confidence, confidence)}")
    conf_run.font.size = Pt(9)
    conf_run.bold = False
    conf_run.font.color.rgb = _GREY

    # Gap warning
    if gap_flag:
        p = doc.add_paragraph()
        warn = p.add_run(f"Knowledge-base gap: {_sanitize(gap_flag)}")
        warn.italic = True
        warn.font.color.rgb = _WARN_COLOUR

    # Body content — priority: finalised > user_edits > draft_text
    raw_content: str = (
        section.get("finalised_content")
        or section.get("user_edits")
        or section.get("draft_text")
        or ""
    )
    content = _sanitize(raw_content)

    if content:
        for para_block in content.split("\n\n"):
            # Each block may still contain single \n (soft line breaks within a para)
            lines = [l.strip() for l in para_block.split("\n") if l.strip()]
            if not lines:
                continue
            p = doc.add_paragraph()
            for j, line in enumerate(lines):
                if j > 0:
                    p.add_run().add_break()  # soft line break between lines in same block
                p.add_run(line)
    else:
        p = doc.add_paragraph()
        p.add_run("[No content generated for this section]").italic = True

    # Sources footer
    sources = section.get("sources_used", [])
    if sources:
        p = doc.add_paragraph()
        run = p.add_run("Sources: " + " · ".join(_sanitize(s) for s in sources))
        run.font.size = Pt(9)
        run.italic = True
        run.font.color.rgb = _GREY

    # Visual separator
    doc.add_paragraph()
