"""
DOCX output renderer — visual match to the DocxPreview component.

Layout order:
  1. Cover page     — navy block, title, org, "Technical" tag
  2. Meta row       — gray bar, "Generated by TenderFlow AI Agent"
  3. Tender Sections — one per page: blue heading + HR, body, sources
  4. Readiness Assessment (end of document)

Content priority per section:
  finalised_content > user_edits > draft_text
"""

import logging
import os
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from config.settings import settings

logger = logging.getLogger(__name__)

# ── Colour palette (mirrors DocxPreview.css) ───────────────────────────────────
_BLUE_HEADING  = RGBColor(0x1A, 0x5F, 0x8A)   # #1a5f8a — section headings
_NAVY          = RGBColor(0x1D, 0x35, 0x57)    # #1d3557 — cover bg, table header
_NAVY_HEX      = "1D3557"
_LIGHT_ROW_HEX = "F7F9FC"                       # odd body rows
_GREY          = RGBColor(0x88, 0x88, 0x88)    # sources label
_WARN_COLOUR   = RGBColor(0xE7, 0x4C, 0x3C)
_SOURCE_BLUE   = RGBColor(0x1A, 0x5F, 0x8A)

# ── Regex helpers ──────────────────────────────────────────────────────────────
_XML_ILLEGAL       = re.compile(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]')
_MARKDOWN_BOLD_IT  = re.compile(r'\*{1,3}([^*]+)\*{1,3}')
_MARKDOWN_HEADING  = re.compile(r'^#{1,6}\s+', re.MULTILINE)
_TABLE_ROW         = re.compile(r'^\s*\|.+\|\s*$')
_TABLE_SEP         = re.compile(r'^\s*\|[\s\-:|]+\|\s*$')


# ── Text helpers ───────────────────────────────────────────────────────────────

def _sanitize(text: str) -> str:
    """Strip XML-illegal chars and markdown syntax."""
    text = _XML_ILLEGAL.sub('', text).replace('\r\n', '\n').replace('\r', '\n')
    text = _MARKDOWN_BOLD_IT.sub(r'\1', text)
    text = _MARKDOWN_HEADING.sub('', text)
    return text


def _sanitize_cell(text: str) -> str:
    return _XML_ILLEGAL.sub('', text).replace('\r\n', ' ').replace('\r', ' ').replace('\n', ' ')


def _is_table_row(line: str) -> bool:
    return bool(_TABLE_ROW.match(line))


def _is_separator_row(line: str) -> bool:
    return bool(_TABLE_SEP.match(line))


def _parse_row_cells(line: str) -> list[str]:
    parts = line.strip().split('|')
    return [_sanitize_cell(p.strip()) for p in parts[1:-1]]


def _is_bold_cell(text: str) -> bool:
    return text.startswith('**') and text.endswith('**')


def _unwrap_bold(text: str) -> str:
    return _MARKDOWN_BOLD_IT.sub(r'\1', text)


def _score_band(score: float) -> str:
    if score >= 90: return "EXCELLENT"
    if score >= 75: return "STRONG"
    if score >= 60: return "MODERATE"
    return "WEAK"


# ── OOXML paragraph helpers ────────────────────────────────────────────────────

def _set_para_bottom_border(p, color_hex: str = "1A5F8A", sz: int = 16) -> None:
    """Add a bottom border to a paragraph (simulates the heading HR in the preview)."""
    pPr = p._p.get_or_add_pPr()
    # Remove existing pBdr if present
    existing = pPr.find(qn('w:pBdr'))
    if existing is not None:
        pPr.remove(existing)
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), str(sz))   # sz=16 → 2pt
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), color_hex)
    pBdr.append(bottom)
    pPr.append(pBdr)


def _shade_cell(cell, fill_hex: str) -> None:
    """Apply a solid background colour to a table cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    # Remove existing shd
    existing = tcPr.find(qn('w:shd'))
    if existing is not None:
        tcPr.remove(existing)
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), fill_hex)
    tcPr.append(shd)


# ── Table renderer ─────────────────────────────────────────────────────────────

def _add_docx_table(doc: Document, rows: list[list[str]]) -> None:
    """Render parsed markdown table rows as a styled DOCX table.

    Header row: navy bg (#1d3557), white bold text.
    Body rows:  odd  → #f7f9fc (light blue-grey)
                even → white
    """
    if not rows:
        return

    col_count = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=col_count)
    table.style = "Table Grid"

    for ri, row_cells in enumerate(rows):
        tr = table.rows[ri]
        is_header = (ri == 0)
        is_odd_body = (not is_header) and (ri % 2 == 1)  # rows 1,3,5… → light bg

        for ci in range(col_count):
            cell_text = row_cells[ci] if ci < len(row_cells) else ""
            is_bold_content = _is_bold_cell(cell_text)
            clean_text = _unwrap_bold(cell_text)

            cell = tr.cells[ci]
            cell.text = ""
            p = cell.paragraphs[0]
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after = Pt(2)
            run = p.add_run(clean_text)
            run.font.size = Pt(10)

            if is_header:
                run.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                _shade_cell(cell, _NAVY_HEX)
            elif is_odd_body:
                _shade_cell(cell, _LIGHT_ROW_HEX)

            if is_bold_content and not is_header:
                run.bold = True

    doc.add_paragraph()  # spacing after table


# ── Content renderer ───────────────────────────────────────────────────────────

def _render_content(doc: Document, text: str) -> None:
    """
    Render section body text.
    Routes lines to: markdown tables → DOCX tables
                     ### / ## / # headings → styled paragraphs
                     x.y sub-section headers → bold paragraph
                     bullets / numbered lists
                     prose paragraphs (justified)
    """
    lines = text.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # ── Markdown table block ──────────────────────────────────────────
        if _is_table_row(stripped):
            table_lines = []
            while i < len(lines) and _is_table_row(lines[i].strip()):
                table_lines.append(lines[i].strip())
                i += 1
            parsed_rows = []
            for tl in table_lines:
                if _is_separator_row(tl):
                    continue
                cells = _parse_row_cells(tl)
                if cells:
                    parsed_rows.append(cells)
            _add_docx_table(doc, parsed_rows)
            continue

        # ── Markdown headings — colour-matched to CSS ─────────────────────
        # h1 (#1a5f8a), h2 (#1d3557), h3 (#333333)
        h3 = stripped.startswith('### ')
        h2 = stripped.startswith('## ')
        h1 = stripped.startswith('# ')
        if h3 or h2 or h1:
            prefix_len = 4 if h3 else 3 if h2 else 2
            heading_text = _sanitize(stripped[prefix_len:])
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(10)
            p.paragraph_format.space_after = Pt(4)
            run = p.add_run(heading_text)
            run.bold = True
            run.font.size = Pt(11 if h1 else 10.5 if h2 else 10)
            run.font.color.rgb = (
                _BLUE_HEADING if h1 else
                _NAVY        if h2 else
                RGBColor(0x33, 0x33, 0x33)
            )
            i += 1
            continue

        # ── Numbered sub-section headers like "3.1 Something" ────────────
        subsection = re.match(r'^(\d+\.\d+)\s+(.+)$', stripped)
        if subsection and len(stripped) < 80:
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(8)
            p.paragraph_format.space_after = Pt(3)
            run = p.add_run(f"{subsection.group(1)} {_sanitize(subsection.group(2))}")
            run.bold = True
            run.font.size = Pt(10.5)
            run.font.color.rgb = _NAVY
            i += 1
            continue

        # ── Bullet list ───────────────────────────────────────────────────
        if stripped.startswith(('- ', '• ', '* ')):
            while i < len(lines) and lines[i].strip().startswith(('- ', '• ', '* ')):
                item = _sanitize(lines[i].strip()[2:])
                p = doc.add_paragraph(style='List Bullet')
                p.paragraph_format.space_after = Pt(2)
                _add_inline_run(p, item)
                i += 1
            continue

        # ── Numbered list ─────────────────────────────────────────────────
        num_match = re.match(r'^\d+[.)]\s+', stripped)
        if num_match:
            while i < len(lines):
                nl = lines[i].strip()
                if not re.match(r'^\d+[.)]\s+', nl):
                    break
                item = _sanitize(re.sub(r'^\d+[.)]\s+', '', nl))
                p = doc.add_paragraph(style='List Number')
                p.paragraph_format.space_after = Pt(2)
                _add_inline_run(p, item)
                i += 1
            continue

        # ── Regular paragraph (justified) ─────────────────────────────────
        para_lines = []
        while i < len(lines):
            pl = lines[i].strip()
            if not pl:
                break
            if _is_table_row(pl):
                break
            if pl.startswith(('# ', '## ', '### ', '- ', '• ', '* ')):
                break
            if re.match(r'^\d+[.)]\s+', pl):
                break
            para_lines.append(pl)
            i += 1
        if para_lines:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.paragraph_format.space_after = Pt(8)
            _add_inline_run(p, _sanitize(' '.join(para_lines)))


def _add_inline_run(p, text: str) -> None:
    """Add a run to paragraph p, handling **bold** and *italic* markers."""
    parts = re.split(r'(\*\*[^*]+\*\*|\*[^*]+\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = p.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = p.add_run(part[1:-1])
            run.italic = True
        else:
            p.add_run(part)


# ── Document sections ──────────────────────────────────────────────────────────

def _configure_styles(doc: Document) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)


def _add_cover(doc: Document, state: dict) -> None:
    """Navy cover block + gray meta row — matches DocxPreview cover."""
    raw_filename = state.get("tender_filename", "Tender Response")
    tender_title = re.sub(r'\.(pdf|docx?|txt)$', '', raw_filename, flags=re.IGNORECASE)
    tender_title = re.sub(r'[_\-]+', ' ', tender_title).strip()

    # ── Navy cover cell ───────────────────────────────────────────────────
    cover_table = doc.add_table(rows=1, cols=1)
    cover_cell = cover_table.rows[0].cells[0]
    _shade_cell(cover_cell, _NAVY_HEX)

    # "Technical" — top-right feel (right-aligned paragraph inside cell)
    cp0 = cover_cell.paragraphs[0]
    cp0.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    cp0.paragraph_format.space_before = Pt(4)
    r0 = cp0.add_run("Technical")
    r0.italic = True
    r0.font.size = Pt(10)
    r0.font.color.rgb = RGBColor(0xA8, 0xC4, 0xE0)

    # Title
    cp1 = cover_cell.add_paragraph()
    cp1.alignment = WD_ALIGN_PARAGRAPH.LEFT
    cp1.paragraph_format.space_before = Pt(8)
    cp1.paragraph_format.space_after = Pt(10)
    r1 = cp1.add_run(tender_title)
    r1.bold = True
    r1.font.size = Pt(20)
    r1.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    # Org name
    cp2 = cover_cell.add_paragraph()
    cp2.paragraph_format.space_after = Pt(20)
    r2 = cp2.add_run("Meridian Intelligence GmbH")
    r2.italic = True
    r2.font.size = Pt(12)
    r2.font.color.rgb = RGBColor(0xA8, 0xC4, 0xE0)

    # ── Gray meta row — "Generated by   TenderFlow AI Agent" ─────────────
    meta_table = doc.add_table(rows=1, cols=1)
    meta_cell = meta_table.rows[0].cells[0]
    _shade_cell(meta_cell, "F0F4F8")

    mp = meta_cell.paragraphs[0]
    mp.paragraph_format.space_before = Pt(6)
    mp.paragraph_format.space_after = Pt(6)

    label_run = mp.add_run("Generated by    ")
    label_run.bold = True
    label_run.font.size = Pt(10)
    label_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)

    value_run = mp.add_run("TenderFlow AI Agent")
    value_run.font.size = Pt(10)
    value_run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)

    doc.add_paragraph()  # spacing before first section


def _add_section(doc: Document, section: dict) -> None:
    """Render one tender section — matches the DocxPreview section card."""
    section_name = section.get("section_name", "Untitled Section")
    gap_flag = section.get("gap_flag")

    # Each section on its own page
    doc.add_page_break()

    # ── Section heading — bold blue with bottom border (= CSS border-bottom) ──
    heading_p = doc.add_paragraph()
    heading_p.paragraph_format.space_before = Pt(0)
    heading_p.paragraph_format.space_after = Pt(8)
    run = heading_p.add_run(_sanitize(section_name))
    run.bold = True
    run.font.size = Pt(13)
    run.font.color.rgb = _BLUE_HEADING
    _set_para_bottom_border(heading_p, color_hex="1A5F8A", sz=16)

    # ── Gap warning (subtle, below heading) ───────────────────────────────
    if gap_flag:
        gp = doc.add_paragraph()
        gw = gp.add_run(f"Knowledge-base gap: {_sanitize(gap_flag)}")
        gw.italic = True
        gw.font.size = Pt(9)
        gw.font.color.rgb = _WARN_COLOUR

    # ── Body content (priority: finalised > user_edits > draft_text) ──────
    raw_content: str = (
        section.get("finalised_content")
        or section.get("user_edits")
        or section.get("draft_text")
        or ""
    )
    raw_content = _XML_ILLEGAL.sub('', raw_content).replace('\r\n', '\n').replace('\r', '\n')

    if raw_content.strip():
        _render_content(doc, raw_content)
    else:
        ep = doc.add_paragraph()
        ep.add_run("[No content generated for this section]").italic = True

    # ── Sources footer — "SOURCES:" + chip-style tags ─────────────────────
    sources = section.get("sources_used", [])
    if sources:
        _add_sources_footer(doc, sources)

    doc.add_paragraph()  # visual gap before next section


def _add_sources_footer(doc: Document, sources: list[str]) -> None:
    """Render a sources row: SOURCES: [tag] [tag] — matches .docx-sources CSS."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(2)
    _set_para_bottom_border_top(p, color_hex="E8EEF4", sz=4)

    label = p.add_run("SOURCES:   ")
    label.font.size = Pt(9)
    label.font.color.rgb = _GREY
    label.bold = True

    for i, src in enumerate(sources):
        if i > 0:
            spacer = p.add_run("  ")
            spacer.font.size = Pt(9)
        tag = p.add_run(_sanitize(src))
        tag.font.size = Pt(9)
        tag.font.color.rgb = _SOURCE_BLUE


def _set_para_bottom_border_top(p, color_hex: str = "E8EEF4", sz: int = 4) -> None:
    """Add a top border to a paragraph (thin separator above sources line)."""
    pPr = p._p.get_or_add_pPr()
    existing = pPr.find(qn('w:pBdr'))
    if existing is not None:
        pPr.remove(existing)
    pBdr = OxmlElement('w:pBdr')
    top = OxmlElement('w:top')
    top.set(qn('w:val'), 'single')
    top.set(qn('w:sz'), str(sz))
    top.set(qn('w:space'), '1')
    top.set(qn('w:color'), color_hex)
    pBdr.append(top)
    pPr.append(pBdr)


# ── Readiness Assessment (appended at end) ────────────────────────────────────

def _add_readiness_assessment(doc: Document, state: dict) -> None:
    doc.add_page_break()

    ra_heading = doc.add_paragraph()
    ra_run = ra_heading.add_run("Readiness Assessment")
    ra_run.bold = True
    ra_run.font.size = Pt(14)
    ra_run.font.color.rgb = _NAVY
    _set_para_bottom_border(ra_heading, color_hex=_NAVY_HEX, sz=16)

    # Score summary table
    score_rows = [
        ("Primary Score", state.get("primary_score_total", 0.0)),
        ("Compliance Coverage", state.get("compliance_score", 0.0)),
        ("Robustness Index", state.get("robustness_score", 0.0)),
        ("Final Score", state.get("final_score", 0.0)),
    ]

    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for ci, label in enumerate(["Dimension", "Score", "Band"]):
        hdr[ci].text = label
        for run in hdr[ci].paragraphs[0].runs:
            run.bold = True
            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        _shade_cell(hdr[ci], _NAVY_HEX)

    for di, (dimension, score) in enumerate(score_rows):
        row = table.add_row().cells
        row[0].text = dimension
        row[1].text = f"{score:.1f} / 100"
        row[2].text = _score_band(score)
        if di % 2 == 0:
            for cell in row:
                _shade_cell(cell, _LIGHT_ROW_HEX)

    doc.add_paragraph()

    # Module breakdown
    primary_scores = state.get("primary_scores", {})
    if primary_scores:
        ph = doc.add_paragraph()
        ph.add_run("Primary Score Breakdown").bold = True

        _MODULE_LABELS = {
            "M1_track_record": "Track Record",
            "M2_expertise_depth": "Expertise Depth",
            "M3_methodology_fit": "Methodology Fit",
            "M4_delivery_credibility": "Delivery Credibility",
            "M5_pricing": "Pricing Proxy",
        }
        mod_table = doc.add_table(rows=1, cols=3)
        mod_table.style = "Table Grid"
        mhdr = mod_table.rows[0].cells
        for ci, label in enumerate(["Module", "Score", "Band"]):
            mhdr[ci].text = label
            for run in mhdr[ci].paragraphs[0].runs:
                run.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
            _shade_cell(mhdr[ci], _NAVY_HEX)
        for di, (key, label) in enumerate(_MODULE_LABELS.items()):
            score = primary_scores.get(key)
            if score is None:
                continue
            mrow = mod_table.add_row().cells
            mrow[0].text = label
            mrow[1].text = f"{score:.0f} / 100"
            mrow[2].text = _score_band(score)
            if di % 2 == 0:
                for cell in mrow:
                    _shade_cell(cell, _LIGHT_ROW_HEX)
        doc.add_paragraph()

    # Score justifications
    justifications = state.get("score_justifications", {})
    if justifications:
        jh = doc.add_paragraph()
        jh.add_run("Score Justifications").bold = True
        for module, justification in justifications.items():
            p = doc.add_paragraph()
            p.add_run(f"{module}:  ").bold = True
            p.add_run(_sanitize(str(justification)))

    # Action items
    ai_heading = doc.add_paragraph()
    ai_heading.add_run("Action Items").bold = True

    sections = state.get("sections", [])
    gap_sections = [s for s in sections if s.get("gap_flag")]
    low_no_gap   = [s for s in sections if s.get("confidence") == "LOW" and not s.get("gap_flag")]

    if gap_sections or low_no_gap:
        for s in gap_sections:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"[{s['section_name']}]  ")
            run.bold = True
            run.font.color.rgb = _WARN_COLOUR
            p.add_run(s["gap_flag"])
        for s in low_no_gap:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"[{s['section_name']}]  ")
            run.bold = True
            run.font.color.rgb = _WARN_COLOUR
            p.add_run(
                "Low-confidence draft — KB content found via fallback retrieval only. "
                "Review and supplement with project-specific evidence."
            )
    else:
        doc.add_paragraph("No critical knowledge-base gaps identified for this tender.")


# ── Public entry point ─────────────────────────────────────────────────────────

def render_docx(state: dict, tender_id: str) -> str:
    """
    Render a complete tender response DOCX from the agent state dict.

    Returns absolute path to the saved .docx file.
    """
    os.makedirs(settings.outputs_dir, exist_ok=True)
    output_path = str(Path(settings.outputs_dir) / f"{tender_id}.docx")

    doc = Document()
    _configure_styles(doc)

    # 1. Cover
    _add_cover(doc, state)

    # 2. Tender sections (each on its own page)
    for section in state.get("sections", []):
        _add_section(doc, section)

    # 3. Readiness Assessment (appended at end, not between cover and content)
    _add_readiness_assessment(doc, state)

    doc.save(output_path)
    logger.info(f"[output] DOCX saved → {output_path}")
    return output_path
